/* levels.js — GENERATED by make-levels.js. Do not edit by hand.
 *
 * A 25-level campaign. The first 5 are written by hand, one rule each;
 * the rest are dealt along a widening curve and kept only if the solver can
 * finish them, their par rises on the level before, and playing them badly
 * still leaves them winnable.
 *
 * par is the true fewest moves, not an estimate. Jar fills are listed BOTTOM
 * first. */
(function (global) {
  'use strict';

  var LEVELS = [
    {
      id: 'level-01',
      name: 'First Pour',
      subtitle: 'Level 1 of 25',
      teaches: 'Picking up and pouring',
      brief: "Tap a jar to pick it up, then tap the big jar to pour. The big jar only ever accepts red, so you cannot spoil it — try the blue and see.",
      target: 'red',
      main: { cap: 4 },
      par: 2,
      jars: [
        { cap: 4, fills: ['red', 'red'] },
        { cap: 4, fills: ['blue', 'blue', 'blue'] },
        { cap: 4, fills: ['red', 'red'] }
      ]
    },
    {
      id: 'level-02',
      name: 'Gather It Up',
      subtitle: 'Level 2 of 25',
      teaches: 'Collecting from several jars',
      brief: "The blue is spread around, but all of it is already on top. Every last drop has to go in — the big jar must be full.",
      target: 'blue',
      main: { cap: 4 },
      par: 3,
      jars: [
        { cap: 4, fills: ['blue', 'blue'] },
        { cap: 4, fills: ['green', 'blue'] },
        { cap: 4, fills: ['green', 'green'] },
        { cap: 4, fills: ['blue'] }
      ]
    },
    {
      id: 'level-03',
      name: 'Out of the Way',
      subtitle: 'Level 3 of 25',
      teaches: 'Uncovering a buried colour',
      brief: "Some yellow is trapped under blue. A colour can be poured onto the same colour, so move the blue onto the blue and the yellow is free.",
      target: 'yellow',
      main: { cap: 4 },
      par: 3,
      jars: [
        { cap: 4, fills: ['yellow', 'yellow', 'blue', 'blue'] },
        { cap: 4, fills: ['blue'] },
        { cap: 4, fills: ['yellow', 'yellow'] }
      ]
    },
    {
      id: 'level-04',
      name: 'Mind the Room',
      subtitle: 'Level 4 of 25',
      teaches: 'Only what fits will move',
      brief: "A pour stops when the jar it is going into runs out of room, so a block of colour can be split across two jars.",
      target: 'teal',
      main: { cap: 5 },
      par: 3,
      jars: [
        { cap: 5, fills: ['teal', 'teal', 'red', 'red', 'red'] },
        { cap: 3, fills: ['red'] },
        { cap: 5, fills: ['teal', 'teal', 'teal'] },
        { cap: 3, fills: [] }
      ]
    },
    {
      id: 'level-05',
      name: 'Empty Space',
      subtitle: 'Level 5 of 25',
      teaches: 'Working through an empty jar',
      brief: "Nothing matches this time. An empty jar takes any colour, so it is the way in — but there is only one, so think before you fill it.",
      target: 'green',
      main: { cap: 6 },
      par: 5,
      jars: [
        { cap: 4, fills: ['green', 'green', 'red', 'red'] },
        { cap: 4, fills: ['green', 'green', 'blue', 'blue'] },
        { cap: 4, fills: ['green', 'green'] },
        { cap: 4, fills: [] },
        { cap: 4, fills: ['red', 'blue'] }
      ]
    },
    {
      id: 'level-06',
      name: 'Stacked Yellow',
      subtitle: 'Level 6 of 25',
      teaches: '6 jars · 7 moves',
      brief: '',
      target: 'yellow',
      main: { cap: 5 },
      par: 7,
      jars: [
        { cap: 4, fills: ['yellow', 'purple', 'slate', 'yellow'] },
        { cap: 4, fills: ['purple', 'magenta', 'slate', 'slate'] },
        { cap: 4, fills: ['slate'] },
        { cap: 4, fills: ['yellow', 'slate'] },
        { cap: 4, fills: ['magenta'] },
        { cap: 4, fills: ['yellow', 'yellow'] }
      ]
    },
    {
      id: 'level-07',
      name: 'Buried Red',
      subtitle: 'Level 7 of 25',
      teaches: '6 jars · 8 moves',
      brief: '',
      target: 'red',
      main: { cap: 5 },
      par: 8,
      jars: [
        { cap: 4, fills: ['yellow', 'blue'] },
        { cap: 4, fills: ['red', 'yellow', 'red', 'yellow'] },
        { cap: 4, fills: ['green', 'yellow', 'red', 'green'] },
        { cap: 4, fills: ['red'] },
        { cap: 4, fills: [] },
        { cap: 4, fills: ['yellow', 'red'] }
      ]
    },
    {
      id: 'level-08',
      name: 'Layered Slate',
      subtitle: 'Level 8 of 25',
      teaches: '7 jars · 10 moves',
      brief: '',
      target: 'slate',
      main: { cap: 6 },
      par: 10,
      jars: [
        { cap: 4, fills: ['teal', 'teal', 'white'] },
        { cap: 4, fills: ['slate'] },
        { cap: 4, fills: ['slate', 'teal'] },
        { cap: 4, fills: ['teal', 'teal'] },
        { cap: 4, fills: ['slate', 'teal', 'blue', 'white'] },
        { cap: 4, fills: ['teal', 'slate', 'slate', 'blue'] },
        { cap: 4, fills: ['slate'] }
      ]
    },
    {
      id: 'level-09',
      name: 'Sunken Yellow',
      subtitle: 'Level 9 of 25',
      teaches: '7 jars · 11 moves',
      brief: '',
      target: 'yellow',
      main: { cap: 6 },
      par: 11,
      jars: [
        { cap: 4, fills: ['yellow', 'red', 'green', 'purple'] },
        { cap: 4, fills: ['yellow', 'red', 'yellow', 'green'] },
        { cap: 4, fills: ['green', 'green'] },
        { cap: 4, fills: [] },
        { cap: 4, fills: ['red'] },
        { cap: 4, fills: ['yellow', 'red'] },
        { cap: 4, fills: ['teal', 'yellow', 'yellow'] }
      ]
    },
    {
      id: 'level-10',
      name: 'Packed White',
      subtitle: 'Level 10 of 25',
      teaches: '7 jars · 15 moves',
      brief: '',
      target: 'white',
      main: { cap: 7 },
      par: 15,
      jars: [
        { cap: 5, fills: ['white'] },
        { cap: 5, fills: ['white', 'purple', 'red', 'green', 'magenta'] },
        { cap: 5, fills: ['purple', 'purple', 'white'] },
        { cap: 5, fills: ['purple', 'red', 'green', 'white', 'magenta'] },
        { cap: 5, fills: ['magenta', 'green', 'white', 'purple'] },
        { cap: 5, fills: ['white', 'red'] },
        { cap: 5, fills: ['white', 'red'] }
      ]
    },
    {
      id: 'level-11',
      name: 'Tangled Orange',
      subtitle: 'Level 11 of 25',
      teaches: '7 jars · 15 moves',
      brief: '',
      target: 'orange',
      main: { cap: 7 },
      par: 15,
      jars: [
        { cap: 5, fills: ['orange', 'purple', 'blue'] },
        { cap: 5, fills: ['blue', 'orange'] },
        { cap: 5, fills: ['purple', 'orange', 'blue', 'slate'] },
        { cap: 5, fills: ['orange', 'purple', 'red', 'red', 'orange'] },
        { cap: 5, fills: ['red', 'purple', 'orange', 'slate'] },
        { cap: 5, fills: ['slate', 'blue'] },
        { cap: 5, fills: ['orange', 'slate'] }
      ]
    },
    {
      id: 'level-12',
      name: 'Jumbled Purple',
      subtitle: 'Level 12 of 25',
      teaches: '8 jars · 15 moves',
      brief: '',
      target: 'purple',
      main: { cap: 8 },
      par: 15,
      jars: [
        { cap: 5, fills: ['purple', 'purple', 'white', 'green', 'magenta'] },
        { cap: 5, fills: ['green', 'green'] },
        { cap: 5, fills: ['purple', 'yellow'] },
        { cap: 5, fills: ['magenta', 'purple', 'purple', 'yellow'] },
        { cap: 5, fills: ['green', 'white', 'green'] },
        { cap: 5, fills: ['white'] },
        { cap: 5, fills: ['purple', 'green', 'yellow', 'white'] },
        { cap: 5, fills: ['purple', 'purple', 'white', 'white', 'yellow'] }
      ]
    },
    {
      id: 'level-13',
      name: 'Deep Orange',
      subtitle: 'Level 13 of 25',
      teaches: '8 jars · 16 moves',
      brief: '',
      target: 'orange',
      main: { cap: 8 },
      par: 16,
      jars: [
        { cap: 5, fills: ['orange', 'magenta', 'purple'] },
        { cap: 5, fills: ['orange', 'orange', 'red'] },
        { cap: 5, fills: ['orange', 'purple', 'magenta'] },
        { cap: 5, fills: ['orange', 'teal'] },
        { cap: 5, fills: ['teal', 'orange'] },
        { cap: 5, fills: ['red', 'teal', 'orange', 'teal', 'teal'] },
        { cap: 5, fills: ['magenta', 'red'] },
        { cap: 5, fills: ['teal', 'magenta', 'orange', 'purple', 'teal'] }
      ]
    },
    {
      id: 'level-14',
      name: 'Crowded Yellow',
      subtitle: 'Level 14 of 25',
      teaches: '8 jars · 17 moves',
      brief: '',
      target: 'yellow',
      main: { cap: 9 },
      par: 17,
      jars: [
        { cap: 5, fills: ['red', 'yellow', 'purple', 'yellow', 'purple'] },
        { cap: 5, fills: ['yellow', 'purple'] },
        { cap: 5, fills: ['yellow', 'yellow', 'purple', 'teal'] },
        { cap: 5, fills: ['teal', 'yellow', 'red'] },
        { cap: 5, fills: ['white', 'red'] },
        { cap: 5, fills: ['yellow'] },
        { cap: 5, fills: ['purple', 'yellow', 'white', 'slate'] },
        { cap: 5, fills: ['red', 'teal', 'yellow', 'slate'] }
      ]
    },
    {
      id: 'level-15',
      name: 'Knotted Teal',
      subtitle: 'Level 15 of 25',
      teaches: '8 jars · 18 moves',
      brief: '',
      target: 'teal',
      main: { cap: 9 },
      par: 18,
      jars: [
        { cap: 5, fills: ['teal', 'slate', 'white', 'magenta'] },
        { cap: 5, fills: ['white', 'magenta', 'teal'] },
        { cap: 5, fills: [] },
        { cap: 5, fills: ['teal', 'teal', 'slate'] },
        { cap: 5, fills: ['teal', 'green'] },
        { cap: 5, fills: ['teal', 'teal', 'green', 'green', 'purple'] },
        { cap: 5, fills: ['teal', 'green', 'purple', 'green'] },
        { cap: 5, fills: ['green', 'teal', 'white'] }
      ]
    },
    {
      id: 'level-16',
      name: 'Folded Magenta',
      subtitle: 'Level 16 of 25',
      teaches: '9 jars · 20 moves',
      brief: '',
      target: 'magenta',
      main: { cap: 10 },
      par: 20,
      jars: [
        { cap: 6, fills: ['blue', 'purple', 'yellow', 'yellow', 'white'] },
        { cap: 6, fills: ['magenta', 'magenta', 'white', 'purple', 'white', 'purple'] },
        { cap: 6, fills: ['yellow', 'magenta', 'blue', 'yellow'] },
        { cap: 6, fills: ['magenta', 'teal', 'purple'] },
        { cap: 6, fills: ['magenta', 'teal', 'teal', 'yellow', 'yellow'] },
        { cap: 6, fills: ['magenta', 'yellow', 'yellow', 'blue'] },
        { cap: 6, fills: ['teal', 'purple', 'teal'] },
        { cap: 6, fills: ['blue', 'white'] },
        { cap: 6, fills: ['magenta', 'blue', 'magenta', 'magenta', 'magenta'] }
      ]
    },
    {
      id: 'level-17',
      name: 'Heaped Yellow',
      subtitle: 'Level 17 of 25',
      teaches: '9 jars · 22 moves',
      brief: '',
      target: 'yellow',
      main: { cap: 10 },
      par: 22,
      jars: [
        { cap: 6, fills: ['purple', 'yellow', 'blue', 'blue'] },
        { cap: 6, fills: ['blue', 'green', 'green', 'white', 'green'] },
        { cap: 6, fills: ['blue', 'yellow', 'teal', 'blue', 'green', 'blue'] },
        { cap: 6, fills: ['teal'] },
        { cap: 6, fills: ['yellow', 'purple'] },
        { cap: 6, fills: ['yellow', 'blue', 'purple', 'yellow'] },
        { cap: 6, fills: ['yellow', 'purple', 'teal', 'white', 'blue', 'purple'] },
        { cap: 6, fills: ['green', 'teal', 'yellow'] },
        { cap: 6, fills: ['green', 'yellow', 'yellow', 'yellow', 'purple'] }
      ]
    },
    {
      id: 'level-18',
      name: 'Wedged Magenta',
      subtitle: 'Level 18 of 25',
      teaches: '9 jars · 24 moves',
      brief: '',
      target: 'magenta',
      main: { cap: 11 },
      par: 24,
      jars: [
        { cap: 6, fills: ['magenta', 'green', 'teal', 'green'] },
        { cap: 6, fills: ['magenta', 'green', 'slate'] },
        { cap: 6, fills: ['green', 'teal', 'magenta', 'green'] },
        { cap: 6, fills: ['orange'] },
        { cap: 6, fills: ['red', 'magenta', 'magenta', 'teal', 'slate'] },
        { cap: 6, fills: ['magenta', 'teal', 'blue', 'green', 'red', 'teal'] },
        { cap: 6, fills: ['magenta', 'magenta'] },
        { cap: 6, fills: ['magenta', 'magenta', 'blue', 'slate', 'blue', 'magenta'] },
        { cap: 6, fills: ['blue', 'red', 'orange', 'blue', 'red'] }
      ]
    },
    {
      id: 'level-19',
      name: 'Sealed Yellow',
      subtitle: 'Level 19 of 25',
      teaches: '9 jars · 26 moves',
      brief: '',
      target: 'yellow',
      main: { cap: 11 },
      par: 26,
      jars: [
        { cap: 6, fills: ['yellow', 'yellow', 'yellow', 'green'] },
        { cap: 6, fills: ['yellow', 'green', 'purple', 'magenta'] },
        { cap: 6, fills: ['yellow', 'white', 'blue', 'red', 'blue'] },
        { cap: 6, fills: ['yellow', 'red', 'white', 'green', 'magenta'] },
        { cap: 6, fills: ['white', 'red', 'red'] },
        { cap: 6, fills: ['yellow', 'yellow', 'green', 'red', 'purple', 'blue'] },
        { cap: 6, fills: ['yellow', 'yellow', 'magenta', 'blue'] },
        { cap: 6, fills: ['green', 'magenta'] },
        { cap: 6, fills: ['yellow', 'red'] }
      ]
    },
    {
      id: 'level-20',
      name: 'Nested Blue',
      subtitle: 'Level 20 of 25',
      teaches: '10 jars · 29 moves',
      brief: '',
      target: 'blue',
      main: { cap: 12 },
      par: 29,
      jars: [
        { cap: 6, fills: ['blue', 'blue', 'magenta'] },
        { cap: 6, fills: ['orange', 'red', 'orange'] },
        { cap: 6, fills: ['blue', 'purple'] },
        { cap: 6, fills: ['blue', 'red', 'orange', 'red', 'orange'] },
        { cap: 6, fills: ['blue', 'orange', 'slate', 'red', 'teal', 'slate'] },
        { cap: 6, fills: ['blue', 'orange', 'magenta'] },
        { cap: 6, fills: ['blue', 'blue', 'red'] },
        { cap: 6, fills: ['blue', 'blue', 'blue', 'slate', 'teal', 'magenta'] },
        { cap: 6, fills: ['blue', 'slate', 'magenta', 'purple', 'teal', 'teal'] },
        { cap: 6, fills: ['teal', 'red', 'purple'] }
      ]
    },
    {
      id: 'level-21',
      name: 'Hidden Yellow',
      subtitle: 'Level 21 of 25',
      teaches: '10 jars · 30 moves',
      brief: '',
      target: 'yellow',
      main: { cap: 12 },
      par: 30,
      jars: [
        { cap: 6, fills: ['yellow', 'yellow', 'teal', 'slate', 'blue', 'blue'] },
        { cap: 6, fills: ['yellow', 'yellow', 'yellow', 'purple', 'blue', 'blue'] },
        { cap: 6, fills: ['yellow', 'slate', 'magenta'] },
        { cap: 6, fills: ['yellow', 'magenta', 'teal', 'teal', 'magenta'] },
        { cap: 6, fills: ['yellow', 'magenta', 'magenta', 'purple', 'slate'] },
        { cap: 6, fills: ['yellow', 'teal', 'purple'] },
        { cap: 6, fills: ['yellow', 'red', 'magenta', 'red', 'red'] },
        { cap: 6, fills: ['teal', 'magenta'] },
        { cap: 6, fills: ['yellow', 'magenta'] },
        { cap: 6, fills: ['yellow', 'teal', 'magenta'] }
      ]
    },
    {
      id: 'level-22',
      name: 'Pressed Yellow',
      subtitle: 'Level 22 of 25',
      teaches: '10 jars · 35 moves',
      brief: '',
      target: 'yellow',
      main: { cap: 13 },
      par: 35,
      jars: [
        { cap: 7, fills: ['teal', 'white', 'white'] },
        { cap: 7, fills: ['yellow', 'blue'] },
        { cap: 7, fills: ['yellow', 'teal', 'white', 'blue', 'purple', 'red', 'blue'] },
        { cap: 7, fills: ['red', 'green', 'teal', 'teal'] },
        { cap: 7, fills: ['yellow', 'purple', 'white', 'white', 'red'] },
        { cap: 7, fills: ['white', 'yellow', 'red', 'purple', 'green', 'red'] },
        { cap: 7, fills: ['yellow', 'blue', 'purple'] },
        { cap: 7, fills: ['yellow', 'teal', 'blue', 'white', 'red', 'blue', 'green'] },
        { cap: 7, fills: ['yellow', 'yellow', 'purple', 'blue', 'teal'] },
        { cap: 7, fills: ['yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'green', 'blue'] }
      ]
    },
    {
      id: 'level-23',
      name: 'Bottled Red',
      subtitle: 'Level 23 of 25',
      teaches: '10 jars · 39 moves',
      brief: '',
      target: 'red',
      main: { cap: 13 },
      par: 39,
      jars: [
        { cap: 7, fills: ['red', 'white', 'slate', 'teal', 'slate'] },
        { cap: 7, fills: ['red', 'slate', 'blue', 'magenta', 'blue'] },
        { cap: 7, fills: ['red', 'red'] },
        { cap: 7, fills: ['red', 'slate', 'purple', 'white', 'teal'] },
        { cap: 7, fills: ['red', 'red', 'blue'] },
        { cap: 7, fills: ['red', 'magenta', 'purple', 'white', 'teal'] },
        { cap: 7, fills: ['red', 'red', 'white', 'green', 'magenta', 'green', 'slate'] },
        { cap: 7, fills: ['red', 'slate', 'blue', 'white', 'purple', 'magenta'] },
        { cap: 7, fills: ['red', 'red', 'magenta', 'purple', 'white'] },
        { cap: 7, fills: ['blue', 'white', 'green', 'purple', 'teal'] }
      ]
    },
    {
      id: 'level-24',
      name: 'Locked Red',
      subtitle: 'Level 24 of 25',
      teaches: '11 jars · 39 moves',
      brief: '',
      target: 'red',
      main: { cap: 14 },
      par: 39,
      jars: [
        { cap: 7, fills: ['red', 'blue', 'orange'] },
        { cap: 7, fills: ['red', 'red', 'slate', 'orange'] },
        { cap: 7, fills: ['red', 'white', 'slate', 'teal', 'slate', 'orange'] },
        { cap: 7, fills: ['red', 'purple', 'slate'] },
        { cap: 7, fills: ['red', 'slate', 'white', 'orange', 'teal', 'white', 'teal'] },
        { cap: 7, fills: ['red', 'orange', 'purple'] },
        { cap: 7, fills: ['red', 'blue', 'teal', 'teal', 'white', 'purple', 'magenta'] },
        { cap: 7, fills: ['orange', 'teal', 'magenta', 'orange', 'white', 'blue', 'purple'] },
        { cap: 7, fills: ['red', 'red', 'orange', 'teal', 'slate'] },
        { cap: 7, fills: ['red', 'red', 'red', 'red', 'magenta', 'white', 'orange'] },
        { cap: 7, fills: ['teal', 'magenta', 'purple'] }
      ]
    },
    {
      id: 'level-25',
      name: 'Drowned Green',
      subtitle: 'Level 25 of 25',
      teaches: '11 jars · 41 moves',
      brief: '',
      target: 'green',
      main: { cap: 14 },
      par: 41,
      jars: [
        { cap: 7, fills: ['slate', 'green'] },
        { cap: 7, fills: ['green', 'green', 'purple', 'orange', 'magenta', 'purple', 'slate'] },
        { cap: 7, fills: ['green', 'orange', 'magenta', 'blue', 'orange', 'slate', 'magenta'] },
        { cap: 7, fills: ['green', 'magenta', 'red', 'magenta'] },
        { cap: 7, fills: ['green', 'blue', 'white', 'red', 'orange', 'orange', 'red'] },
        { cap: 7, fills: ['green', 'green', 'blue', 'blue', 'slate', 'magenta', 'purple'] },
        { cap: 7, fills: ['green', 'green', 'green', 'orange', 'blue', 'white'] },
        { cap: 7, fills: ['orange', 'red', 'magenta', 'slate', 'red'] },
        { cap: 7, fills: ['green', 'orange'] },
        { cap: 7, fills: ['green', 'magenta', 'orange'] },
        { cap: 7, fills: ['green', 'slate', 'red', 'red'] }
      ]
    }
  ];

  global.Levels = {
    list: LEVELS,
    byId: function (id) {
      for (var i = 0; i < LEVELS.length; i++) if (LEVELS[i].id === id) return LEVELS[i];
      return null;
    },
    indexOf: function (id) {
      for (var i = 0; i < LEVELS.length; i++) if (LEVELS[i].id === id) return i;
      return -1;
    }
  };
})(typeof window !== 'undefined' ? window : globalThis);
