/* merge-levels.js — GENERATED by tools/make-merge-levels.js.
 *
 * The first 5 are written by hand, one lesson each, and are carried through
 * every rebuild untouched. The rest are dealt along a widening curve and kept
 * only if the search can finish them quickly enough to answer a hint, their
 * par rises on the level before, and careless play cannot deadlock them.
 *
 * Only the two parents of the target ever appear as mixable colours, so no
 * wrong merge is possible: everything else on the shelf is inert.
 *
 * par is the true fewest moves. Jar fills are listed BOTTOM first. */
(function (global) {
  'use strict';

  var LEVELS = [
    {
      id: 'merge-01',
      mode: 'merge',
      name: 'Red and Blue',
      subtitle: 'Level 1 of 25',
      teaches: 'Mixing two colours',
      brief: "There is no purple on the shelf — you have to make it. Pour the red onto the blue and watch what happens, then fill the big jar.",
      target: 'purple',
      main: { cap: 2 },
      par: 2,
      path: [[0,1], [1,-1]],
      jars: [
        { cap: 4, fills: ['red', 'red'] },
        { cap: 4, fills: ['blue', 'blue'] }
      ]
    },
    {
      id: 'merge-02',
      mode: 'merge',
      name: 'Only What Pairs',
      subtitle: 'Level 2 of 25',
      teaches: 'Mixing takes one for one',
      brief: "Three reds, two blues. Colours mix one for one, so only two of the reds have anything to pair with — the rest stays put.",
      target: 'purple',
      main: { cap: 2 },
      par: 2,
      path: [[1,0], [0,-1]],
      jars: [
        { cap: 4, fills: ['red', 'red', 'red'] },
        { cap: 4, fills: ['blue', 'blue'] }
      ]
    },
    {
      id: 'merge-03',
      mode: 'merge',
      name: 'Out of the Way',
      subtitle: 'Level 3 of 25',
      teaches: 'Clearing a colour that will not mix',
      brief: "Blue and yellow make green, but the slate on top mixes with nothing at all. Park it in the empty jar first.",
      target: 'green',
      main: { cap: 3 },
      par: 3,
      path: [[1,2], [0,1], [1,-1]],
      jars: [
        { cap: 4, fills: ['blue', 'blue', 'blue'] },
        { cap: 4, fills: ['yellow', 'yellow', 'yellow', 'slate'] },
        { cap: 4, fills: [] }
      ]
    },
    {
      id: 'merge-04',
      mode: 'merge',
      name: 'Gather First',
      subtitle: 'Level 4 of 25',
      teaches: 'Gathering a colour before mixing it',
      brief: "Mixing pairs one for one, so a bigger pile of yellow makes a bigger pour of orange. Put the two yellows together before you reach for the red — and mind that blue, which would take the red for itself.",
      target: 'orange',
      main: { cap: 4 },
      par: 3,
      path: [[1,2], [2,0], [0,-1]],
      jars: [
        { cap: 6, fills: ['red', 'red', 'red', 'red', 'red', 'red'] },
        { cap: 4, fills: ['yellow', 'yellow'] },
        { cap: 4, fills: ['yellow', 'yellow'] },
        { cap: 4, fills: ['blue', 'blue'] }
      ]
    },
    {
      id: 'merge-05',
      mode: 'merge',
      name: 'Every Last Drop',
      subtitle: 'Level 5 of 25',
      teaches: 'All three together, with nothing to spare',
      brief: "Four purple needed and exactly four reds to make it, two of them under the yellow. Clear it, gather the red, and mix it into the blue where it stands — and do not let the yellow have any.",
      target: 'purple',
      main: { cap: 4 },
      par: 4,
      path: [[1,3], [1,2], [2,0], [0,-1]],
      jars: [
        { cap: 6, fills: ['blue', 'blue', 'blue', 'blue', 'blue', 'blue'] },
        { cap: 4, fills: ['red', 'red', 'yellow', 'yellow'] },
        { cap: 4, fills: ['red', 'red'] },
        { cap: 4, fills: ['yellow', 'yellow'] },
        { cap: 4, fills: [] }
      ]
    },
    {
      id: 'merge-06',
      mode: 'merge',
      name: 'Stirred Green',
      subtitle: 'Level 6 of 25',
      teaches: '4 jars · 5 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 3 },
      par: 5,
      path: [[2,0], [2,0], [0,-1], [1,0], [0,-1]],
      jars: [
        { cap: 4, fills: ['blue', 'yellow'] },
        { cap: 4, fills: ['white', 'white', 'yellow'] },
        { cap: 4, fills: ['blue', 'blue', 'yellow'] },
        { cap: 4, fills: ['white', 'white'] }
      ]
    },
    {
      id: 'merge-07',
      mode: 'merge',
      name: 'Folded Green',
      subtitle: 'Level 7 of 25',
      teaches: '4 jars · 6 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 3 },
      par: 6,
      path: [[3,2], [3,0], [1,3], [2,1], [3,1], [1,-1]],
      jars: [
        { cap: 4, fills: ['teal', 'teal'] },
        { cap: 4, fills: ['teal', 'yellow', 'blue'] },
        { cap: 4, fills: ['yellow'] },
        { cap: 4, fills: ['blue', 'blue', 'teal', 'yellow'] }
      ]
    },
    {
      id: 'merge-08',
      mode: 'merge',
      name: 'Steeped Green',
      subtitle: 'Level 8 of 25',
      teaches: '4 jars · 6 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 3 },
      par: 6,
      path: [[0,3], [3,-1], [2,0], [1,3], [2,1], [1,-1]],
      jars: [
        { cap: 4, fills: ['yellow', 'yellow'] },
        { cap: 4, fills: ['yellow', 'white'] },
        { cap: 4, fills: ['white', 'blue', 'white', 'white'] },
        { cap: 4, fills: ['blue', 'blue'] }
      ]
    },
    {
      id: 'merge-09',
      mode: 'merge',
      name: 'Tinted Orange',
      subtitle: 'Level 9 of 25',
      teaches: '4 jars · 9 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 4 },
      par: 9,
      path: [[2,0], [2,1], [3,2], [1,3], [1,0], [3,1], [0,3], [1,3], [3,-1]],
      jars: [
        { cap: 4, fills: ['yellow'] },
        { cap: 4, fills: ['red', 'yellow', 'red'] },
        { cap: 4, fills: ['red', 'yellow'] },
        { cap: 4, fills: ['yellow', 'red', 'magenta', 'magenta'] }
      ]
    },
    {
      id: 'merge-10',
      mode: 'merge',
      name: 'Blended Orange',
      subtitle: 'Level 10 of 25',
      teaches: '5 jars · 10 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 4 },
      par: 10,
      path: [[2,0], [1,4], [2,1], [3,2], [3,1], [2,3], [0,2], [3,0], [0,1], [1,-1]],
      jars: [
        { cap: 5, fills: ['red', 'slate'] },
        { cap: 5, fills: ['yellow', 'magenta'] },
        { cap: 5, fills: ['slate', 'red', 'yellow', 'yellow', 'slate'] },
        { cap: 5, fills: ['slate', 'magenta', 'red', 'yellow', 'red'] },
        { cap: 5, fills: ['slate', 'magenta'] }
      ]
    },
    {
      id: 'merge-11',
      mode: 'merge',
      name: 'Swirled Purple',
      subtitle: 'Level 11 of 25',
      teaches: '5 jars · 12 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 4 },
      par: 12,
      path: [[0,1], [0,3], [2,0], [0,-1], [2,0], [1,0], [1,3], [3,-1], [2,1], [4,3], [2,4], [4,-1]],
      jars: [
        { cap: 4, fills: ['blue', 'red', 'teal'] },
        { cap: 4, fills: ['blue', 'blue', 'teal'] },
        { cap: 4, fills: ['red', 'green', 'teal', 'red'] },
        { cap: 4, fills: ['red'] },
        { cap: 4, fills: ['blue', 'teal'] }
      ]
    },
    {
      id: 'merge-12',
      mode: 'merge',
      name: 'Clouded Orange',
      subtitle: 'Level 12 of 25',
      teaches: '5 jars · 12 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 4 },
      par: 12,
      path: [[3,4], [1,3], [3,1], [1,-1], [2,1], [3,2], [2,-1], [0,2], [3,0], [0,-1], [0,3], [3,-1]],
      jars: [
        { cap: 5, fills: ['red', 'yellow', 'green', 'green', 'green'] },
        { cap: 5, fills: ['purple', 'red', 'yellow'] },
        { cap: 5, fills: ['red', 'purple'] },
        { cap: 5, fills: ['yellow', 'red', 'yellow', 'green'] },
        { cap: 5, fills: ['purple', 'green'] }
      ]
    },
    {
      id: 'merge-13',
      mode: 'merge',
      name: 'Deepened Orange',
      subtitle: 'Level 13 of 25',
      teaches: '5 jars · 13 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 5 },
      par: 13,
      path: [[4,0], [4,3], [4,0], [1,4], [4,-1], [3,1], [0,4], [2,0], [2,0], [0,-1], [0,3], [2,3], [3,-1]],
      jars: [
        { cap: 5, fills: ['red', 'yellow', 'magenta'] },
        { cap: 5, fills: ['yellow'] },
        { cap: 5, fills: ['yellow', 'yellow', 'red', 'red', 'yellow'] },
        { cap: 5, fills: ['red', 'white', 'white'] },
        { cap: 5, fills: ['red', 'magenta', 'white', 'magenta'] }
      ]
    },
    {
      id: 'merge-14',
      mode: 'merge',
      name: 'Layered Orange',
      subtitle: 'Level 14 of 25',
      teaches: '5 jars · 14 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 4 },
      par: 14,
      path: [[4,0], [4,2], [4,3], [3,-1], [2,4], [3,2], [2,-1], [1,2], [3,1], [1,-1], [0,3], [0,4], [0,1], [1,-1]],
      jars: [
        { cap: 5, fills: ['yellow', 'slate', 'magenta'] },
        { cap: 5, fills: ['red', 'yellow', 'slate'] },
        { cap: 5, fills: ['red', 'slate'] },
        { cap: 5, fills: ['red', 'yellow', 'red'] },
        { cap: 5, fills: ['yellow', 'slate', 'slate', 'slate', 'magenta'] }
      ]
    },
    {
      id: 'merge-15',
      mode: 'merge',
      name: 'Muddled Green',
      subtitle: 'Level 15 of 25',
      teaches: '5 jars · 14 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 5 },
      par: 14,
      path: [[0,1], [2,0], [1,2], [3,0], [0,-1], [1,0], [4,1], [4,2], [1,3], [4,1], [0,4], [0,1], [1,4], [4,-1]],
      jars: [
        { cap: 5, fills: ['blue', 'yellow', 'blue', 'white'] },
        { cap: 5, fills: ['blue', 'teal', 'yellow', 'white'] },
        { cap: 5, fills: ['blue'] },
        { cap: 5, fills: ['yellow', 'yellow'] },
        { cap: 5, fills: ['yellow', 'blue', 'white', 'teal', 'teal'] }
      ]
    },
    {
      id: 'merge-16',
      mode: 'merge',
      name: 'Wound Green',
      subtitle: 'Level 16 of 25',
      teaches: '6 jars · 14 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 5 },
      par: 14,
      path: [[5,1], [5,0], [3,5], [3,4], [5,3], [5,4], [2,5], [2,0], [2,1], [4,2], [0,4], [0,2], [2,4], [4,-1]],
      jars: [
        { cap: 5, fills: ['blue', 'yellow'] },
        { cap: 5, fills: ['purple'] },
        { cap: 5, fills: ['blue', 'purple', 'yellow', 'slate'] },
        { cap: 5, fills: ['slate', 'magenta', 'blue', 'magenta', 'magenta'] },
        { cap: 5, fills: ['yellow', 'blue'] },
        { cap: 5, fills: ['blue', 'magenta', 'yellow', 'yellow', 'purple'] }
      ]
    },
    {
      id: 'merge-17',
      mode: 'merge',
      name: 'Sunken Green',
      subtitle: 'Level 17 of 25',
      teaches: '6 jars · 16 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 6 },
      par: 16,
      path: [[3,0], [0,-1], [1,0], [3,1], [1,-1], [1,0], [1,4], [3,1], [1,3], [3,-1], [4,1], [2,3], [2,4], [2,5], [5,4], [4,-1]],
      jars: [
        { cap: 5, fills: ['blue'] },
        { cap: 5, fills: ['yellow', 'magenta', 'white', 'yellow', 'white'] },
        { cap: 5, fills: ['yellow', 'blue', 'purple'] },
        { cap: 5, fills: ['blue', 'blue', 'yellow', 'blue', 'yellow'] },
        { cap: 5, fills: ['blue', 'magenta', 'magenta'] },
        { cap: 5, fills: ['purple', 'yellow'] }
      ]
    },
    {
      id: 'merge-18',
      mode: 'merge',
      name: 'Threaded Purple',
      subtitle: 'Level 18 of 25',
      teaches: '6 jars · 17 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 5 },
      par: 17,
      path: [[3,0], [0,-1], [5,3], [5,1], [1,0], [2,1], [5,4], [5,2], [1,5], [4,2], [2,-1], [4,3], [2,0], [4,2], [4,1], [2,1], [1,-1]],
      jars: [
        { cap: 5, fills: ['orange', 'blue'] },
        { cap: 5, fills: ['white', 'blue', 'magenta', 'orange'] },
        { cap: 5, fills: ['red', 'orange', 'blue', 'magenta'] },
        { cap: 5, fills: ['red'] },
        { cap: 5, fills: ['blue', 'red', 'white', 'red'] },
        { cap: 5, fills: ['blue', 'red', 'orange', 'white'] }
      ]
    },
    {
      id: 'merge-19',
      mode: 'merge',
      name: 'Scattered Green',
      subtitle: 'Level 19 of 25',
      teaches: '6 jars · 18 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 6 },
      par: 18,
      path: [[2,1], [2,4], [1,2], [3,1], [1,-1], [3,5], [1,3], [5,1], [3,5], [3,0], [5,4], [4,-1], [0,5], [0,1], [0,4], [0,3], [3,4], [4,-1]],
      jars: [
        { cap: 5, fills: ['blue', 'yellow', 'magenta', 'purple'] },
        { cap: 5, fills: ['yellow', 'blue', 'white'] },
        { cap: 5, fills: ['blue', 'blue', 'white'] },
        { cap: 5, fills: ['blue', 'purple', 'yellow', 'magenta', 'yellow'] },
        { cap: 5, fills: ['yellow', 'blue'] },
        { cap: 5, fills: ['yellow', 'magenta'] }
      ]
    },
    {
      id: 'merge-20',
      mode: 'merge',
      name: 'Buried Purple',
      subtitle: 'Level 20 of 25',
      teaches: '6 jars · 18 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 6 },
      par: 18,
      path: [[3,2], [1,0], [0,-1], [0,5], [0,3], [4,0], [4,5], [4,2], [1,4], [3,1], [3,2], [4,1], [1,-1], [2,4], [1,2], [1,3], [2,3], [3,-1]],
      jars: [
        { cap: 5, fills: ['red', 'slate', 'blue'] },
        { cap: 5, fills: ['red', 'blue', 'red', 'blue', 'red'] },
        { cap: 5, fills: ['blue', 'white'] },
        { cap: 5, fills: ['red', 'white', 'red', 'white'] },
        { cap: 5, fills: ['blue', 'blue', 'white', 'slate', 'magenta'] },
        { cap: 5, fills: [] }
      ]
    },
    {
      id: 'merge-21',
      mode: 'merge',
      name: 'Knotted Purple',
      subtitle: 'Level 21 of 25',
      teaches: '6 jars · 21 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 6 },
      par: 21,
      path: [[0,5], [0,3], [3,0], [0,-1], [5,0], [3,5], [1,5], [1,0], [1,3], [3,-1], [5,1], [4,1], [2,3], [5,2], [2,-1], [5,2], [2,-1], [4,5], [4,1], [2,4], [4,-1]],
      jars: [
        { cap: 6, fills: ['red', 'red', 'blue', 'green', 'green'] },
        { cap: 6, fills: ['red', 'green', 'white'] },
        { cap: 6, fills: ['red', 'blue', 'red', 'slate'] },
        { cap: 6, fills: ['blue', 'white', 'blue'] },
        { cap: 6, fills: ['blue', 'white', 'green', 'white'] },
        { cap: 6, fills: ['red', 'blue', 'white', 'green'] }
      ]
    },
    {
      id: 'merge-22',
      mode: 'merge',
      name: 'Split Green',
      subtitle: 'Level 22 of 25',
      teaches: '7 jars · 22 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 7 },
      par: 22,
      path: [[6,3], [6,4], [4,-1], [5,6], [2,1], [0,1], [5,2], [0,5], [0,2], [0,2], [2,-1], [5,0], [3,2], [3,4], [5,3], [3,-1], [3,2], [4,0], [5,3], [4,5], [3,5], [5,-1]],
      jars: [
        { cap: 6, fills: ['yellow', 'yellow', 'yellow', 'blue', 'slate', 'orange'] },
        { cap: 6, fills: ['white', 'orange'] },
        { cap: 6, fills: ['blue', 'orange', 'orange'] },
        { cap: 6, fills: ['yellow', 'purple', 'yellow', 'slate', 'purple'] },
        { cap: 6, fills: ['blue', 'slate', 'yellow'] },
        { cap: 6, fills: ['blue', 'yellow', 'blue', 'slate', 'blue', 'white'] },
        { cap: 6, fills: ['blue', 'purple'] }
      ]
    },
    {
      id: 'merge-23',
      mode: 'merge',
      name: 'Braided Purple',
      subtitle: 'Level 23 of 25',
      teaches: '7 jars · 24 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 6 },
      par: 24,
      path: [[6,0], [5,3], [2,3], [6,2], [1,2], [1,0], [1,3], [0,1], [0,2], [0,6], [0,5], [4,0], [4,2], [5,4], [4,6], [6,-1], [2,4], [1,6], [1,2], [5,1], [1,-1], [5,1], [2,5], [5,-1]],
      jars: [
        { cap: 6, fills: ['red', 'blue', 'white', 'magenta'] },
        { cap: 6, fills: ['red', 'blue', 'magenta', 'orange', 'magenta', 'white'] },
        { cap: 6, fills: ['blue', 'white', 'orange'] },
        { cap: 6, fills: ['orange'] },
        { cap: 6, fills: ['red', 'white', 'green'] },
        { cap: 6, fills: ['red', 'red', 'green', 'blue', 'red', 'orange'] },
        { cap: 6, fills: ['blue', 'blue', 'white', 'magenta'] }
      ]
    },
    {
      id: 'merge-24',
      mode: 'merge',
      name: 'Fractured Purple',
      subtitle: 'Level 24 of 25',
      teaches: '7 jars · 25 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 7 },
      par: 25,
      path: [[6,3], [6,1], [6,4], [4,-1], [4,1], [0,4], [6,0], [0,-1], [0,5], [0,6], [1,0], [2,1], [2,0], [1,2], [1,6], [2,1], [2,0], [2,6], [2,5], [4,2], [4,5], [4,6], [5,4], [4,6], [6,-1]],
      jars: [
        { cap: 6, fills: ['red', 'blue', 'red', 'teal'] },
        { cap: 6, fills: ['red', 'white', 'orange'] },
        { cap: 6, fills: ['blue', 'red', 'orange', 'white', 'orange', 'white'] },
        { cap: 6, fills: [] },
        { cap: 6, fills: ['blue', 'red', 'blue', 'teal', 'orange', 'blue'] },
        { cap: 6, fills: ['slate', 'slate', 'blue'] },
        { cap: 6, fills: ['red', 'blue', 'red', 'orange', 'slate'] }
      ]
    },
    {
      id: 'merge-25',
      mode: 'merge',
      name: 'Distilled Green',
      subtitle: 'Level 25 of 25',
      teaches: '7 jars · 25 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 7 },
      par: 25,
      path: [[5,6], [5,2], [5,4], [3,1], [1,0], [3,1], [5,3], [3,-1], [5,3], [3,-1], [4,3], [5,4], [4,-1], [4,0], [2,4], [1,5], [1,2], [4,1], [2,4], [6,2], [0,2], [6,0], [4,6], [0,6], [6,-1]],
      jars: [
        { cap: 6, fills: ['yellow', 'magenta'] },
        { cap: 6, fills: ['blue', 'slate', 'magenta'] },
        { cap: 6, fills: ['blue', 'teal'] },
        { cap: 6, fills: ['blue', 'yellow', 'slate', 'magenta'] },
        { cap: 6, fills: ['blue', 'teal', 'magenta', 'yellow', 'orange'] },
        { cap: 6, fills: ['blue', 'yellow', 'blue', 'orange', 'teal', 'magenta'] },
        { cap: 6, fills: ['blue', 'yellow', 'yellow', 'yellow', 'magenta'] }
      ]
    }
  ];

  global.MergeLevels = {
    list: LEVELS,
    byId: function (id) {
      for (var i = 0; i < LEVELS.length; i++) if (LEVELS[i].id === id) return LEVELS[i];
      return null;
    },
    indexOf: function (id) {
      for (var i = 0; i < LEVELS.length; i++) if (LEVELS[i].id === id) return i;
      return -1;
    }
  };
})(typeof window !== 'undefined' ? window : globalThis);
