/* merge-levels.js — GENERATED by tools/make-merge-levels.js.
 *
 * The first 5 are written by hand, one lesson each, and are carried through
 * every rebuild untouched. The rest are dealt along a widening curve and kept
 * only if the search can finish them quickly enough to answer a hint, their
 * par rises on the level before, and careless play cannot deadlock them.
 *
 * Only the two parents of the target ever appear as mixable colours, so no
 * wrong merge is possible: everything else on the shelf is inert.
 *
 * par is the true fewest moves. Jar fills are listed BOTTOM first. */
(function (global) {
  'use strict';

  var LEVELS = [
    {
      id: 'merge-01',
      mode: 'merge',
      name: 'Red and Blue',
      subtitle: 'Level 1 of 50',
      teaches: 'Mixing two colours',
      brief: "There is no purple on the shelf — you have to make it. Pour the red onto the blue and watch what happens, then fill the big jar.",
      target: 'purple',
      main: { cap: 2 },
      par: 2,
      path: [[0,1], [1,-1]],
      jars: [
        { cap: 4, fills: ['red', 'red'] },
        { cap: 4, fills: ['blue', 'blue'] }
      ]
    },
    {
      id: 'merge-02',
      mode: 'merge',
      name: 'Only What Pairs',
      subtitle: 'Level 2 of 50',
      teaches: 'Mixing takes one for one',
      brief: "Three reds, two blues. Colours mix one for one, so only two of the reds have anything to pair with — the rest stays put.",
      target: 'purple',
      main: { cap: 2 },
      par: 2,
      path: [[1,0], [0,-1]],
      jars: [
        { cap: 4, fills: ['red', 'red', 'red'] },
        { cap: 4, fills: ['blue', 'blue'] }
      ]
    },
    {
      id: 'merge-03',
      mode: 'merge',
      name: 'Out of the Way',
      subtitle: 'Level 3 of 50',
      teaches: 'Clearing a colour that will not mix',
      brief: "Blue and yellow make green, but the cyan on top mixes with nothing at all. Park it in the empty jar first.",
      target: 'green',
      main: { cap: 3 },
      par: 3,
      path: [[1,2], [0,1], [1,-1]],
      jars: [
        { cap: 4, fills: ['blue', 'blue', 'blue'] },
        { cap: 4, fills: ['yellow', 'yellow', 'yellow', 'slate'] },
        { cap: 4, fills: [] }
      ]
    },
    {
      id: 'merge-04',
      mode: 'merge',
      name: 'Gather First',
      subtitle: 'Level 4 of 50',
      teaches: 'Gathering a colour before mixing it',
      brief: "Mixing pairs one for one, so a bigger pile of yellow makes a bigger pour of orange. Put the two yellows together before you reach for the red — and mind that blue, which would take the red for itself.",
      target: 'orange',
      main: { cap: 4 },
      par: 3,
      path: [[1,2], [2,0], [0,-1]],
      jars: [
        { cap: 6, fills: ['red', 'red', 'red', 'red', 'red', 'red'] },
        { cap: 4, fills: ['yellow', 'yellow'] },
        { cap: 4, fills: ['yellow', 'yellow'] },
        { cap: 4, fills: ['blue', 'blue'] }
      ]
    },
    {
      id: 'merge-05',
      mode: 'merge',
      name: 'Every Last Drop',
      subtitle: 'Level 5 of 50',
      teaches: 'All three together, with nothing to spare',
      brief: "Four purple needed and exactly four reds to make it, two of them under the yellow. Clear it, gather the red, and mix it into the blue where it stands — and do not let the yellow have any.",
      target: 'purple',
      main: { cap: 4 },
      par: 4,
      path: [[1,3], [1,2], [2,0], [0,-1]],
      jars: [
        { cap: 6, fills: ['blue', 'blue', 'blue', 'blue', 'blue', 'blue'] },
        { cap: 4, fills: ['red', 'red', 'yellow', 'yellow'] },
        { cap: 4, fills: ['red', 'red'] },
        { cap: 4, fills: ['yellow', 'yellow'] },
        { cap: 4, fills: [] }
      ]
    },
    {
      id: 'merge-06',
      mode: 'merge',
      name: 'Stirred Green',
      subtitle: 'Level 6 of 50',
      teaches: '4 jars · 5 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 3 },
      par: 5,
      path: [[2,0], [2,0], [0,-1], [1,0], [0,-1]],
      jars: [
        { cap: 4, fills: ['blue', 'yellow'] },
        { cap: 4, fills: ['white', 'white', 'yellow'] },
        { cap: 4, fills: ['blue', 'blue', 'yellow'] },
        { cap: 4, fills: ['white', 'white'] }
      ]
    },
    {
      id: 'merge-07',
      mode: 'merge',
      name: 'Folded Green',
      subtitle: 'Level 7 of 50',
      teaches: '4 jars · 6 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 3 },
      par: 6,
      path: [[3,2], [3,0], [1,3], [2,1], [3,1], [1,-1]],
      jars: [
        { cap: 4, fills: ['teal', 'teal'] },
        { cap: 4, fills: ['teal', 'yellow', 'blue'] },
        { cap: 4, fills: ['yellow'] },
        { cap: 4, fills: ['blue', 'blue', 'teal', 'yellow'] }
      ]
    },
    {
      id: 'merge-08',
      mode: 'merge',
      name: 'Steeped Green',
      subtitle: 'Level 8 of 50',
      teaches: '4 jars · 6 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 3 },
      par: 6,
      path: [[0,3], [3,-1], [2,0], [1,3], [2,1], [1,-1]],
      jars: [
        { cap: 4, fills: ['yellow', 'yellow'] },
        { cap: 4, fills: ['yellow', 'white'] },
        { cap: 4, fills: ['white', 'blue', 'white', 'white'] },
        { cap: 4, fills: ['blue', 'blue'] }
      ]
    },
    {
      id: 'merge-09',
      mode: 'merge',
      name: 'Tinted Orange',
      subtitle: 'Level 9 of 50',
      teaches: '4 jars · 9 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 4 },
      par: 9,
      path: [[2,0], [2,1], [3,2], [1,3], [1,0], [3,1], [0,3], [1,3], [3,-1]],
      jars: [
        { cap: 4, fills: ['yellow'] },
        { cap: 4, fills: ['red', 'yellow', 'red'] },
        { cap: 4, fills: ['red', 'yellow'] },
        { cap: 4, fills: ['yellow', 'red', 'magenta', 'magenta'] }
      ]
    },
    {
      id: 'merge-10',
      mode: 'merge',
      name: 'Blended Orange',
      subtitle: 'Level 10 of 50',
      teaches: '5 jars · 10 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 4 },
      par: 10,
      path: [[2,0], [1,4], [2,1], [3,2], [3,1], [2,3], [0,2], [3,0], [0,1], [1,-1]],
      jars: [
        { cap: 5, fills: ['red', 'slate'] },
        { cap: 5, fills: ['yellow', 'magenta'] },
        { cap: 5, fills: ['slate', 'red', 'yellow', 'yellow', 'slate'] },
        { cap: 5, fills: ['slate', 'magenta', 'red', 'yellow', 'red'] },
        { cap: 5, fills: ['slate', 'magenta'] }
      ]
    },
    {
      id: 'merge-11',
      mode: 'merge',
      name: 'Swirled Purple',
      subtitle: 'Level 11 of 50',
      teaches: '5 jars · 12 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 4 },
      par: 12,
      path: [[0,1], [0,3], [2,0], [0,-1], [2,0], [1,0], [1,3], [3,-1], [2,1], [4,3], [2,4], [4,-1]],
      jars: [
        { cap: 4, fills: ['blue', 'red', 'teal'] },
        { cap: 4, fills: ['blue', 'blue', 'teal'] },
        { cap: 4, fills: ['red', 'green', 'teal', 'red'] },
        { cap: 4, fills: ['red'] },
        { cap: 4, fills: ['blue', 'teal'] }
      ]
    },
    {
      id: 'merge-12',
      mode: 'merge',
      name: 'Clouded Orange',
      subtitle: 'Level 12 of 50',
      teaches: '5 jars · 12 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 4 },
      par: 12,
      path: [[3,4], [1,3], [3,1], [1,-1], [2,1], [3,2], [2,-1], [0,2], [3,0], [0,-1], [0,3], [3,-1]],
      jars: [
        { cap: 5, fills: ['red', 'yellow', 'green', 'green', 'green'] },
        { cap: 5, fills: ['purple', 'red', 'yellow'] },
        { cap: 5, fills: ['red', 'purple'] },
        { cap: 5, fills: ['yellow', 'red', 'yellow', 'green'] },
        { cap: 5, fills: ['purple', 'green'] }
      ]
    },
    {
      id: 'merge-13',
      mode: 'merge',
      name: 'Deepened Orange',
      subtitle: 'Level 13 of 50',
      teaches: '5 jars · 13 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 5 },
      par: 13,
      path: [[4,0], [4,3], [4,0], [1,4], [4,-1], [3,1], [0,4], [2,0], [2,0], [0,-1], [0,3], [2,3], [3,-1]],
      jars: [
        { cap: 5, fills: ['red', 'yellow', 'magenta'] },
        { cap: 5, fills: ['yellow'] },
        { cap: 5, fills: ['yellow', 'yellow', 'red', 'red', 'yellow'] },
        { cap: 5, fills: ['red', 'white', 'white'] },
        { cap: 5, fills: ['red', 'magenta', 'white', 'magenta'] }
      ]
    },
    {
      id: 'merge-14',
      mode: 'merge',
      name: 'Layered Orange',
      subtitle: 'Level 14 of 50',
      teaches: '5 jars · 14 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 4 },
      par: 14,
      path: [[4,0], [4,2], [4,3], [3,-1], [2,4], [3,2], [2,-1], [1,2], [3,1], [1,-1], [0,3], [0,4], [0,1], [1,-1]],
      jars: [
        { cap: 5, fills: ['yellow', 'slate', 'magenta'] },
        { cap: 5, fills: ['red', 'yellow', 'slate'] },
        { cap: 5, fills: ['red', 'slate'] },
        { cap: 5, fills: ['red', 'yellow', 'red'] },
        { cap: 5, fills: ['yellow', 'slate', 'slate', 'slate', 'magenta'] }
      ]
    },
    {
      id: 'merge-15',
      mode: 'merge',
      name: 'Muddled Green',
      subtitle: 'Level 15 of 50',
      teaches: '5 jars · 14 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 5 },
      par: 14,
      path: [[0,1], [2,0], [1,2], [3,0], [0,-1], [1,0], [4,1], [4,2], [1,3], [4,1], [0,4], [0,1], [1,4], [4,-1]],
      jars: [
        { cap: 5, fills: ['blue', 'yellow', 'blue', 'white'] },
        { cap: 5, fills: ['blue', 'teal', 'yellow', 'white'] },
        { cap: 5, fills: ['blue'] },
        { cap: 5, fills: ['yellow', 'yellow'] },
        { cap: 5, fills: ['yellow', 'blue', 'white', 'teal', 'teal'] }
      ]
    },
    {
      id: 'merge-16',
      mode: 'merge',
      name: 'Wound Green',
      subtitle: 'Level 16 of 50',
      teaches: '6 jars · 14 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 5 },
      par: 14,
      path: [[5,1], [5,0], [3,5], [3,4], [5,3], [5,4], [2,5], [2,0], [2,1], [4,2], [0,4], [0,2], [2,4], [4,-1]],
      jars: [
        { cap: 5, fills: ['blue', 'yellow'] },
        { cap: 5, fills: ['purple'] },
        { cap: 5, fills: ['blue', 'purple', 'yellow', 'slate'] },
        { cap: 5, fills: ['slate', 'magenta', 'blue', 'magenta', 'magenta'] },
        { cap: 5, fills: ['yellow', 'blue'] },
        { cap: 5, fills: ['blue', 'magenta', 'yellow', 'yellow', 'purple'] }
      ]
    },
    {
      id: 'merge-17',
      mode: 'merge',
      name: 'Sunken Green',
      subtitle: 'Level 17 of 50',
      teaches: '6 jars · 16 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 6 },
      par: 16,
      path: [[3,0], [0,-1], [1,0], [3,1], [1,-1], [1,0], [1,4], [3,1], [1,3], [3,-1], [4,1], [2,3], [2,4], [2,5], [5,4], [4,-1]],
      jars: [
        { cap: 5, fills: ['blue'] },
        { cap: 5, fills: ['yellow', 'magenta', 'white', 'yellow', 'white'] },
        { cap: 5, fills: ['yellow', 'blue', 'purple'] },
        { cap: 5, fills: ['blue', 'blue', 'yellow', 'blue', 'yellow'] },
        { cap: 5, fills: ['blue', 'magenta', 'magenta'] },
        { cap: 5, fills: ['purple', 'yellow'] }
      ]
    },
    {
      id: 'merge-18',
      mode: 'merge',
      name: 'Threaded Purple',
      subtitle: 'Level 18 of 50',
      teaches: '6 jars · 17 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 5 },
      par: 17,
      path: [[3,0], [0,-1], [5,3], [5,1], [1,0], [2,1], [5,4], [5,2], [1,5], [4,2], [2,-1], [4,3], [2,0], [4,2], [4,1], [2,1], [1,-1]],
      jars: [
        { cap: 5, fills: ['orange', 'blue'] },
        { cap: 5, fills: ['white', 'blue', 'magenta', 'orange'] },
        { cap: 5, fills: ['red', 'orange', 'blue', 'magenta'] },
        { cap: 5, fills: ['red'] },
        { cap: 5, fills: ['blue', 'red', 'white', 'red'] },
        { cap: 5, fills: ['blue', 'red', 'orange', 'white'] }
      ]
    },
    {
      id: 'merge-19',
      mode: 'merge',
      name: 'Scattered Green',
      subtitle: 'Level 19 of 50',
      teaches: '6 jars · 18 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 6 },
      par: 18,
      path: [[2,1], [2,4], [1,2], [3,1], [1,-1], [3,5], [1,3], [5,1], [3,5], [3,0], [5,4], [4,-1], [0,5], [0,1], [0,4], [0,3], [3,4], [4,-1]],
      jars: [
        { cap: 5, fills: ['blue', 'yellow', 'magenta', 'purple'] },
        { cap: 5, fills: ['yellow', 'blue', 'white'] },
        { cap: 5, fills: ['blue', 'blue', 'white'] },
        { cap: 5, fills: ['blue', 'purple', 'yellow', 'magenta', 'yellow'] },
        { cap: 5, fills: ['yellow', 'blue'] },
        { cap: 5, fills: ['yellow', 'magenta'] }
      ]
    },
    {
      id: 'merge-20',
      mode: 'merge',
      name: 'Buried Purple',
      subtitle: 'Level 20 of 50',
      teaches: '6 jars · 18 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 6 },
      par: 18,
      path: [[3,2], [1,0], [0,-1], [0,5], [0,3], [4,0], [4,5], [4,2], [1,4], [3,1], [3,2], [4,1], [1,-1], [2,4], [1,2], [1,3], [2,3], [3,-1]],
      jars: [
        { cap: 5, fills: ['red', 'slate', 'blue'] },
        { cap: 5, fills: ['red', 'blue', 'red', 'blue', 'red'] },
        { cap: 5, fills: ['blue', 'white'] },
        { cap: 5, fills: ['red', 'white', 'red', 'white'] },
        { cap: 5, fills: ['blue', 'blue', 'white', 'slate', 'magenta'] },
        { cap: 5, fills: [] }
      ]
    },
    {
      id: 'merge-21',
      mode: 'merge',
      name: 'Knotted Purple',
      subtitle: 'Level 21 of 50',
      teaches: '6 jars · 21 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 6 },
      par: 21,
      path: [[0,5], [0,3], [3,0], [0,-1], [5,0], [3,5], [1,5], [1,0], [1,3], [3,-1], [5,1], [4,1], [2,3], [5,2], [2,-1], [5,2], [2,-1], [4,5], [4,1], [2,4], [4,-1]],
      jars: [
        { cap: 6, fills: ['red', 'red', 'blue', 'green', 'green'] },
        { cap: 6, fills: ['red', 'green', 'white'] },
        { cap: 6, fills: ['red', 'blue', 'red', 'slate'] },
        { cap: 6, fills: ['blue', 'white', 'blue'] },
        { cap: 6, fills: ['blue', 'white', 'green', 'white'] },
        { cap: 6, fills: ['red', 'blue', 'white', 'green'] }
      ]
    },
    {
      id: 'merge-22',
      mode: 'merge',
      name: 'Split Green',
      subtitle: 'Level 22 of 50',
      teaches: '7 jars · 22 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 7 },
      par: 22,
      path: [[6,3], [6,4], [4,-1], [5,6], [2,1], [0,1], [5,2], [0,5], [0,2], [0,2], [2,-1], [5,0], [3,2], [3,4], [5,3], [3,-1], [3,2], [4,0], [5,3], [4,5], [3,5], [5,-1]],
      jars: [
        { cap: 6, fills: ['yellow', 'yellow', 'yellow', 'blue', 'slate', 'orange'] },
        { cap: 6, fills: ['white', 'orange'] },
        { cap: 6, fills: ['blue', 'orange', 'orange'] },
        { cap: 6, fills: ['yellow', 'purple', 'yellow', 'slate', 'purple'] },
        { cap: 6, fills: ['blue', 'slate', 'yellow'] },
        { cap: 6, fills: ['blue', 'yellow', 'blue', 'slate', 'blue', 'white'] },
        { cap: 6, fills: ['blue', 'purple'] }
      ]
    },
    {
      id: 'merge-23',
      mode: 'merge',
      name: 'Braided Purple',
      subtitle: 'Level 23 of 50',
      teaches: '7 jars · 24 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 6 },
      par: 24,
      path: [[6,0], [5,3], [2,3], [6,2], [1,2], [1,0], [1,3], [0,1], [0,2], [0,6], [0,5], [4,0], [4,2], [5,4], [4,6], [6,-1], [2,4], [1,6], [1,2], [5,1], [1,-1], [5,1], [2,5], [5,-1]],
      jars: [
        { cap: 6, fills: ['red', 'blue', 'white', 'magenta'] },
        { cap: 6, fills: ['red', 'blue', 'magenta', 'orange', 'magenta', 'white'] },
        { cap: 6, fills: ['blue', 'white', 'orange'] },
        { cap: 6, fills: ['orange'] },
        { cap: 6, fills: ['red', 'white', 'green'] },
        { cap: 6, fills: ['red', 'red', 'green', 'blue', 'red', 'orange'] },
        { cap: 6, fills: ['blue', 'blue', 'white', 'magenta'] }
      ]
    },
    {
      id: 'merge-24',
      mode: 'merge',
      name: 'Fractured Purple',
      subtitle: 'Level 24 of 50',
      teaches: '7 jars · 25 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 7 },
      par: 25,
      path: [[6,3], [6,1], [6,4], [4,-1], [4,1], [0,4], [6,0], [0,-1], [0,5], [0,6], [1,0], [2,1], [2,0], [1,2], [1,6], [2,1], [2,0], [2,6], [2,5], [4,2], [4,5], [4,6], [5,4], [4,6], [6,-1]],
      jars: [
        { cap: 6, fills: ['red', 'blue', 'red', 'teal'] },
        { cap: 6, fills: ['red', 'white', 'orange'] },
        { cap: 6, fills: ['blue', 'red', 'orange', 'white', 'orange', 'white'] },
        { cap: 6, fills: [] },
        { cap: 6, fills: ['blue', 'red', 'blue', 'teal', 'orange', 'blue'] },
        { cap: 6, fills: ['slate', 'slate', 'blue'] },
        { cap: 6, fills: ['red', 'blue', 'red', 'orange', 'slate'] }
      ]
    },
    {
      id: 'merge-25',
      mode: 'merge',
      name: 'Distilled Green',
      subtitle: 'Level 25 of 50',
      teaches: '7 jars · 25 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 7 },
      par: 25,
      path: [[5,6], [5,2], [5,4], [3,1], [1,0], [3,1], [5,3], [3,-1], [5,3], [3,-1], [4,3], [5,4], [4,-1], [4,0], [2,4], [1,5], [1,2], [4,1], [2,4], [6,2], [0,2], [6,0], [4,6], [0,6], [6,-1]],
      jars: [
        { cap: 6, fills: ['yellow', 'magenta'] },
        { cap: 6, fills: ['blue', 'slate', 'magenta'] },
        { cap: 6, fills: ['blue', 'teal'] },
        { cap: 6, fills: ['blue', 'yellow', 'slate', 'magenta'] },
        { cap: 6, fills: ['blue', 'teal', 'magenta', 'yellow', 'orange'] },
        { cap: 6, fills: ['blue', 'yellow', 'blue', 'orange', 'teal', 'magenta'] },
        { cap: 6, fills: ['blue', 'yellow', 'yellow', 'yellow', 'magenta'] }
      ]
    },
    {
      id: 'merge-26',
      mode: 'merge',
      name: 'Churned Purple',
      subtitle: 'Level 26 of 50',
      teaches: '7 jars · 26 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 6 },
      par: 26,
      path: [[6,2], [5,1], [1,0], [1,6], [1,4], [5,1], [6,4], [4,-1], [6,5], [6,2], [6,4], [4,-1], [6,5], [2,4], [2,3], [0,2], [0,1], [0,3], [0,6], [6,-1], [5,0], [2,6], [5,2], [2,-1], [2,5], [5,-1]],
      jars: [
        { cap: 7, fills: ['blue', 'green', 'slate', 'orange'] },
        { cap: 7, fills: ['blue', 'red', 'orange'] },
        { cap: 7, fills: ['blue', 'red', 'orange', 'green', 'magenta'] },
        { cap: 7, fills: ['orange', 'white', 'green'] },
        { cap: 7, fills: ['red', 'blue'] },
        { cap: 7, fills: ['red', 'blue', 'white', 'slate', 'orange'] },
        { cap: 7, fills: ['red', 'white', 'blue', 'magenta', 'white', 'red', 'magenta'] }
      ]
    },
    {
      id: 'merge-27',
      mode: 'merge',
      name: 'Marbled Orange',
      subtitle: 'Level 27 of 50',
      teaches: '5 jars · 26 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 7 },
      par: 26,
      path: [[2,1], [1,-1], [4,1], [4,2], [2,-1], [2,3], [2,4], [2,1], [4,2], [2,-1], [4,2], [2,4], [4,-1], [3,2], [0,4], [3,1], [0,1], [0,3], [3,0], [0,-1], [3,0], [3,0], [0,-1], [3,0], [0,3], [3,-1]],
      jars: [
        { cap: 7, fills: ['yellow', 'red', 'purple', 'slate'] },
        { cap: 7, fills: ['yellow'] },
        { cap: 7, fills: ['yellow', 'purple', 'red', 'white', 'red', 'red'] },
        { cap: 7, fills: ['yellow', 'red', 'yellow', 'red', 'purple', 'white'] },
        { cap: 7, fills: ['yellow', 'red', 'yellow', 'purple'] }
      ]
    },
    {
      id: 'merge-28',
      mode: 'merge',
      name: 'Streaked Green',
      subtitle: 'Level 28 of 50',
      teaches: '6 jars · 26 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 7 },
      par: 26,
      path: [[4,3], [5,4], [2,3], [1,2], [0,5], [1,0], [0,-1], [4,0], [1,2], [5,4], [4,-1], [5,1], [4,5], [5,-1], [3,4], [3,5], [2,5], [2,3], [1,4], [2,1], [1,-1], [3,2], [3,1], [1,-1], [1,3], [3,-1]],
      jars: [
        { cap: 7, fills: ['blue', 'yellow'] },
        { cap: 7, fills: ['blue', 'yellow', 'blue', 'white', 'orange', 'yellow', 'orange'] },
        { cap: 7, fills: ['yellow', 'magenta', 'orange', 'white'] },
        { cap: 7, fills: ['yellow', 'blue', 'magenta', 'orange', 'white'] },
        { cap: 7, fills: ['yellow', 'blue', 'blue', 'slate', 'white'] },
        { cap: 7, fills: ['blue', 'white', 'yellow', 'slate'] }
      ]
    },
    {
      id: 'merge-29',
      mode: 'merge',
      name: 'Riddled Orange',
      subtitle: 'Level 29 of 50',
      teaches: '8 jars · 26 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 10 },
      par: 26,
      path: [[5,6], [5,2], [2,-1], [2,7], [5,2], [7,5], [2,7], [6,2], [5,7], [7,-1], [6,5], [0,7], [6,0], [0,-1], [3,0], [6,3], [3,-1], [4,6], [4,3], [3,-1], [4,5], [1,3], [4,1], [1,-1], [1,4], [4,-1]],
      jars: [
        { cap: 5, fills: ['red', 'white'] },
        { cap: 5, fills: ['yellow', 'red', 'slate'] },
        { cap: 5, fills: ['red', 'yellow', 'yellow', 'red'] },
        { cap: 5, fills: ['red', 'yellow', 'green'] },
        { cap: 5, fills: ['red', 'yellow', 'white', 'yellow', 'magenta'] },
        { cap: 5, fills: ['yellow', 'red', 'red', 'yellow', 'purple'] },
        { cap: 5, fills: ['red', 'yellow', 'white', 'purple'] },
        { cap: 5, fills: ['red', 'yellow'] }
      ]
    },
    {
      id: 'merge-30',
      mode: 'merge',
      name: 'Tangled Orange',
      subtitle: 'Level 30 of 50',
      teaches: '6 jars · 26 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 7 },
      par: 26,
      path: [[5,0], [3,1], [3,4], [2,0], [3,2], [3,1], [5,3], [3,-1], [3,5], [5,-1], [1,3], [1,2], [1,5], [0,5], [1,0], [0,-1], [4,1], [4,0], [0,-1], [2,0], [4,2], [2,-1], [2,5], [2,4], [2,4], [4,-1]],
      jars: [
        { cap: 7, fills: ['red', 'yellow', 'purple'] },
        { cap: 7, fills: ['red', 'purple', 'purple', 'magenta', 'slate'] },
        { cap: 7, fills: ['red', 'yellow', 'purple', 'yellow', 'magenta', 'purple'] },
        { cap: 7, fills: ['red', 'yellow', 'yellow', 'slate', 'magenta', 'purple', 'slate'] },
        { cap: 7, fills: ['red', 'yellow', 'purple'] },
        { cap: 7, fills: ['yellow', 'red', 'red', 'purple', 'purple'] }
      ]
    },
    {
      id: 'merge-31',
      mode: 'merge',
      name: 'Sifted Orange',
      subtitle: 'Level 31 of 50',
      teaches: '6 jars · 26 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 8 },
      par: 26,
      path: [[0,2], [0,5], [5,0], [0,-1], [1,0], [1,5], [5,1], [1,-1], [5,1], [1,5], [5,-1], [2,1], [3,0], [3,5], [2,5], [2,3], [3,2], [2,-1], [4,2], [3,4], [3,1], [4,3], [4,3], [3,-1], [3,4], [4,-1]],
      jars: [
        { cap: 6, fills: ['red', 'yellow', 'teal'] },
        { cap: 6, fills: ['red', 'yellow', 'purple'] },
        { cap: 6, fills: ['red', 'yellow', 'green', 'teal'] },
        { cap: 6, fills: ['red', 'yellow', 'teal', 'yellow', 'green', 'purple'] },
        { cap: 6, fills: ['yellow', 'red', 'red', 'red', 'yellow', 'white'] },
        { cap: 6, fills: ['red', 'yellow'] }
      ]
    },
    {
      id: 'merge-32',
      mode: 'merge',
      name: 'Strewn Green',
      subtitle: 'Level 32 of 50',
      teaches: '6 jars · 27 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 9 },
      par: 27,
      path: [[0,2], [0,1], [2,0], [2,1], [3,4], [3,2], [2,-1], [2,3], [4,2], [2,-1], [1,2], [0,3], [4,1], [1,-1], [1,0], [0,-1], [1,4], [0,5], [1,0], [0,-1], [4,1], [0,4], [5,0], [5,4], [4,-1], [4,5], [5,-1]],
      jars: [
        { cap: 7, fills: ['blue', 'yellow', 'purple', 'yellow', 'white', 'slate', 'white'] },
        { cap: 7, fills: ['blue', 'orange', 'blue', 'yellow', 'slate'] },
        { cap: 7, fills: ['blue', 'blue', 'white', 'yellow', 'slate', 'white'] },
        { cap: 7, fills: ['blue', 'yellow'] },
        { cap: 7, fills: ['yellow', 'blue', 'orange', 'blue', 'yellow'] },
        { cap: 7, fills: ['blue', 'yellow', 'yellow', 'purple'] }
      ]
    },
    {
      id: 'merge-33',
      mode: 'merge',
      name: 'Warped Orange',
      subtitle: 'Level 33 of 50',
      teaches: '6 jars · 27 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 6 },
      par: 27,
      path: [[2,3], [1,0], [2,1], [4,2], [4,2], [2,-1], [4,2], [5,4], [3,5], [1,3], [1,4], [1,5], [2,1], [1,-1], [5,1], [5,2], [2,-1], [3,5], [3,4], [3,2], [2,-1], [3,4], [3,2], [2,-1], [2,3], [2,3], [3,-1]],
      jars: [
        { cap: 7, fills: ['teal', 'white', 'purple'] },
        { cap: 7, fills: ['red', 'green', 'teal', 'white', 'purple'] },
        { cap: 7, fills: ['yellow', 'red', 'yellow', 'red', 'yellow', 'white', 'green'] },
        { cap: 7, fills: ['red', 'teal', 'yellow', 'teal', 'white', 'green'] },
        { cap: 7, fills: ['yellow', 'red', 'yellow'] },
        { cap: 7, fills: ['red', 'green', 'teal'] }
      ]
    },
    {
      id: 'merge-34',
      mode: 'merge',
      name: 'Lodged Purple',
      subtitle: 'Level 34 of 50',
      teaches: '6 jars · 27 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 9 },
      par: 27,
      path: [[0,3], [0,4], [0,2], [5,0], [4,0], [0,-1], [2,4], [0,2], [0,2], [2,-1], [3,0], [3,4], [1,2], [3,5], [5,3], [3,-1], [5,3], [5,1], [1,-1], [5,3], [1,0], [4,1], [5,4], [4,-1], [1,4], [1,5], [5,-1]],
      jars: [
        { cap: 7, fills: ['blue', 'blue', 'red', 'blue', 'teal', 'red', 'orange'] },
        { cap: 7, fills: ['blue', 'teal', 'orange', 'blue', 'green'] },
        { cap: 7, fills: ['red', 'teal'] },
        { cap: 7, fills: ['blue', 'blue', 'red', 'teal', 'orange'] },
        { cap: 7, fills: ['red', 'teal', 'red'] },
        { cap: 7, fills: ['red', 'blue', 'white', 'red', 'white', 'red', 'blue'] }
      ]
    },
    {
      id: 'merge-35',
      mode: 'merge',
      name: 'Ravelled Orange',
      subtitle: 'Level 35 of 50',
      teaches: '6 jars · 27 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 7 },
      par: 27,
      path: [[5,1], [4,0], [4,1], [4,3], [2,4], [1,2], [5,1], [1,-1], [3,1], [5,3], [3,-1], [5,0], [5,3], [3,-1], [5,3], [3,-1], [2,5], [2,0], [2,3], [3,-1], [4,2], [0,3], [0,2], [4,0], [0,-1], [0,4], [4,-1]],
      jars: [
        { cap: 7, fills: ['red', 'yellow', 'slate', 'magenta'] },
        { cap: 7, fills: ['red', 'white', 'white'] },
        { cap: 7, fills: ['yellow', 'magenta', 'white', 'slate'] },
        { cap: 7, fills: ['red', 'yellow', 'red', 'yellow', 'green'] },
        { cap: 7, fills: ['yellow', 'red', 'slate', 'green', 'green', 'white', 'magenta'] },
        { cap: 7, fills: ['red', 'yellow', 'magenta', 'red', 'yellow', 'white'] }
      ]
    },
    {
      id: 'merge-36',
      mode: 'merge',
      name: 'Sundered Purple',
      subtitle: 'Level 36 of 50',
      teaches: '6 jars · 27 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 7 },
      par: 27,
      path: [[5,3], [3,1], [0,1], [3,0], [3,5], [2,3], [0,3], [5,0], [0,-1], [2,0], [1,5], [1,2], [4,1], [0,4], [2,0], [0,-1], [4,0], [4,3], [2,3], [4,2], [2,-1], [4,2], [2,-1], [5,4], [5,3], [2,5], [5,-1]],
      jars: [
        { cap: 7, fills: ['red', 'red', 'orange', 'blue', 'blue', 'green', 'orange'] },
        { cap: 7, fills: ['blue', 'orange'] },
        { cap: 7, fills: ['red', 'blue', 'red', 'green', 'blue', 'orange', 'green'] },
        { cap: 7, fills: ['red', 'green', 'orange'] },
        { cap: 7, fills: ['red', 'blue', 'green', 'orange', 'slate'] },
        { cap: 7, fills: ['blue', 'green', 'orange', 'red', 'orange'] }
      ]
    },
    {
      id: 'merge-37',
      mode: 'merge',
      name: 'Flooded Green',
      subtitle: 'Level 37 of 50',
      teaches: '6 jars · 27 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 5 },
      par: 27,
      path: [[4,1], [3,1], [2,3], [2,1], [2,5], [3,2], [3,1], [4,3], [3,-1], [3,5], [3,1], [2,4], [3,2], [2,-1], [5,3], [2,0], [5,2], [2,-1], [5,2], [0,2], [0,3], [0,4], [0,3], [5,0], [0,-1], [0,5], [5,-1]],
      jars: [
        { cap: 7, fills: ['blue', 'yellow', 'magenta', 'purple', 'magenta', 'teal'] },
        { cap: 7, fills: ['magenta', 'teal'] },
        { cap: 7, fills: ['blue', 'teal', 'yellow', 'purple', 'magenta', 'teal', 'purple'] },
        { cap: 7, fills: ['blue', 'teal', 'magenta', 'yellow', 'teal', 'purple', 'teal'] },
        { cap: 7, fills: ['blue', 'teal'] },
        { cap: 7, fills: ['yellow', 'blue', 'teal', 'yellow', 'magenta'] }
      ]
    },
    {
      id: 'merge-38',
      mode: 'merge',
      name: 'Winnowed Orange',
      subtitle: 'Level 38 of 50',
      teaches: '7 jars · 27 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 6 },
      par: 27,
      path: [[2,3], [6,2], [1,4], [1,0], [6,1], [6,4], [5,1], [5,3], [5,0], [6,5], [5,-1], [2,6], [4,2], [5,4], [4,-1], [5,4], [4,-1], [4,2], [4,5], [5,-1], [3,4], [0,5], [0,2], [3,0], [0,-1], [0,3], [3,-1]],
      jars: [
        { cap: 7, fills: ['yellow', 'red', 'magenta', 'white'] },
        { cap: 7, fills: ['white', 'green', 'white', 'slate', 'slate', 'white', 'magenta'] },
        { cap: 7, fills: ['purple'] },
        { cap: 7, fills: ['red', 'yellow', 'purple'] },
        { cap: 7, fills: ['yellow', 'magenta', 'red', 'yellow', 'magenta'] },
        { cap: 7, fills: ['red', 'yellow', 'red', 'yellow', 'white', 'purple', 'slate'] },
        { cap: 7, fills: ['green', 'slate', 'green', 'red', 'magenta', 'slate', 'green'] }
      ]
    },
    {
      id: 'merge-39',
      mode: 'merge',
      name: 'Harrowed Green',
      subtitle: 'Level 39 of 50',
      teaches: '7 jars · 28 moves',
      brief: "",
      target: 'green',
      parents: ['blue', 'yellow'],
      main: { cap: 10 },
      par: 28,
      path: [[3,1], [0,6], [0,3], [4,0], [4,3], [0,4], [4,3], [3,-1], [2,0], [1,4], [1,3], [2,3], [3,-1], [1,3], [1,2], [6,1], [2,3], [3,-1], [6,2], [5,3], [5,1], [5,3], [6,5], [5,-1], [6,5], [5,-1], [5,6], [6,-1]],
      jars: [
        { cap: 7, fills: ['blue', 'yellow', 'orange'] },
        { cap: 7, fills: ['blue', 'yellow', 'blue', 'purple'] },
        { cap: 7, fills: ['blue', 'yellow', 'yellow', 'white'] },
        { cap: 7, fills: ['yellow', 'blue', 'yellow', 'purple'] },
        { cap: 7, fills: ['blue', 'yellow', 'blue'] },
        { cap: 7, fills: ['blue', 'yellow', 'blue', 'magenta', 'orange', 'magenta'] },
        { cap: 7, fills: ['yellow', 'blue', 'yellow', 'slate', 'orange'] }
      ]
    },
    {
      id: 'merge-40',
      mode: 'merge',
      name: 'Shattered Orange',
      subtitle: 'Level 40 of 50',
      teaches: '6 jars · 28 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 9 },
      par: 28,
      path: [[1,4], [0,1], [0,2], [3,5], [3,0], [0,-1], [5,0], [4,5], [4,3], [3,-1], [4,3], [3,-1], [5,4], [1,5], [1,3], [1,2], [5,1], [3,5], [1,5], [5,-1], [3,5], [3,1], [1,-1], [2,3], [2,1], [1,-1], [2,1], [1,-1]],
      jars: [
        { cap: 7, fills: ['yellow', 'white', 'red'] },
        { cap: 7, fills: ['red', 'yellow', 'red', 'white', 'yellow', 'red', 'slate'] },
        { cap: 7, fills: ['white', 'yellow', 'red', 'white'] },
        { cap: 7, fills: ['yellow', 'magenta', 'yellow', 'red', 'yellow', 'red', 'purple'] },
        { cap: 7, fills: ['yellow', 'red', 'slate'] },
        { cap: 7, fills: ['yellow', 'red', 'slate', 'purple'] }
      ]
    },
    {
      id: 'merge-41',
      mode: 'merge',
      name: 'Interleaved Purple',
      subtitle: 'Level 41 of 50',
      teaches: '7 jars · 28 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 10 },
      par: 28,
      path: [[2,4], [1,2], [6,0], [1,6], [3,5], [1,0], [3,1], [0,1], [1,-1], [6,0], [5,1], [5,3], [3,-1], [5,6], [3,5], [4,3], [5,6], [6,-1], [4,5], [2,6], [4,2], [2,-1], [4,2], [2,-1], [4,2], [2,-1], [2,4], [4,-1]],
      jars: [
        { cap: 7, fills: ['red'] },
        { cap: 7, fills: ['blue', 'red', 'teal', 'orange'] },
        { cap: 7, fills: ['blue', 'red', 'blue', 'red', 'orange', 'white'] },
        { cap: 7, fills: ['blue', 'red', 'blue', 'blue', 'magenta'] },
        { cap: 7, fills: ['red', 'blue', 'red', 'blue', 'green', 'white'] },
        { cap: 7, fills: ['blue', 'red', 'blue', 'magenta'] },
        { cap: 7, fills: ['red', 'teal', 'red'] }
      ]
    },
    {
      id: 'merge-42',
      mode: 'merge',
      name: 'Combed Purple',
      subtitle: 'Level 42 of 50',
      teaches: '7 jars · 28 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 10 },
      par: 28,
      path: [[6,1], [4,0], [6,4], [4,-1], [6,4], [4,-1], [3,6], [3,4], [2,3], [4,2], [2,-1], [5,4], [2,5], [1,5], [2,1], [1,-1], [5,2], [5,1], [1,-1], [5,1], [1,-1], [1,4], [0,5], [1,0], [0,-1], [6,1], [0,6], [6,-1]],
      jars: [
        { cap: 7, fills: ['blue', 'red', 'green'] },
        { cap: 7, fills: ['blue', 'slate', 'red', 'blue', 'red', 'white'] },
        { cap: 7, fills: ['blue', 'white', 'red', 'red', 'red', 'magenta'] },
        { cap: 7, fills: ['blue', 'orange'] },
        { cap: 7, fills: ['blue', 'blue', 'red', 'blue', 'green'] },
        { cap: 7, fills: ['blue', 'red', 'white', 'slate'] },
        { cap: 7, fills: ['red', 'orange', 'blue', 'red', 'white'] }
      ]
    },
    {
      id: 'merge-43',
      mode: 'merge',
      name: 'Sieved Orange',
      subtitle: 'Level 43 of 50',
      teaches: '7 jars · 30 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 8 },
      par: 30,
      path: [[1,5], [5,1], [1,-1], [3,1], [5,3], [3,-1], [2,3], [5,2], [5,3], [5,2], [2,-1], [4,5], [4,2], [4,2], [2,-1], [6,4], [6,2], [6,2], [2,-1], [0,6], [0,4], [0,2], [2,0], [0,-1], [2,0], [2,0], [0,-1], [2,0], [0,2], [2,-1]],
      jars: [
        { cap: 5, fills: ['red', 'yellow', 'purple', 'white'] },
        { cap: 5, fills: ['red', 'yellow'] },
        { cap: 5, fills: ['red', 'yellow', 'red', 'yellow', 'green'] },
        { cap: 5, fills: ['red', 'slate'] },
        { cap: 5, fills: ['red', 'yellow', 'magenta'] },
        { cap: 5, fills: ['red', 'green', 'yellow', 'yellow'] },
        { cap: 5, fills: ['red', 'yellow', 'purple'] }
      ]
    },
    {
      id: 'merge-44',
      mode: 'merge',
      name: 'Decanted Purple',
      subtitle: 'Level 44 of 50',
      teaches: '7 jars · 30 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 8 },
      par: 30,
      path: [[5,4], [5,1], [1,-1], [4,2], [1,5], [4,0], [0,-1], [6,4], [3,4], [0,6], [1,0], [0,-1], [1,0], [0,-1], [6,1], [3,0], [0,-1], [6,3], [6,4], [6,2], [6,1], [3,0], [6,3], [3,-1], [3,6], [1,6], [3,1], [1,-1], [1,3], [3,-1]],
      jars: [
        { cap: 7, fills: ['red', 'blue', 'red', 'teal', 'blue'] },
        { cap: 7, fills: ['blue', 'red', 'teal', 'red', 'blue', 'orange', 'blue'] },
        { cap: 7, fills: ['white'] },
        { cap: 7, fills: ['red', 'blue', 'teal', 'red', 'magenta', 'blue', 'green'] },
        { cap: 7, fills: ['red', 'white'] },
        { cap: 7, fills: ['magenta', 'white', 'orange', 'red', 'white'] },
        { cap: 7, fills: ['blue', 'teal', 'white', 'green', 'magenta', 'teal', 'green'] }
      ]
    },
    {
      id: 'merge-45',
      mode: 'merge',
      name: 'Scrambled Purple',
      subtitle: 'Level 45 of 50',
      teaches: '7 jars · 31 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 9 },
      par: 31,
      path: [[2,6], [0,6], [1,0], [1,2], [6,1], [3,5], [0,3], [0,1], [2,0], [6,2], [2,-1], [5,2], [4,5], [4,2], [4,1], [6,4], [4,-1], [3,6], [3,4], [3,0], [5,3], [4,5], [0,4], [0,3], [5,0], [4,5], [0,4], [5,0], [4,5], [0,5], [5,-1]],
      jars: [
        { cap: 7, fills: ['blue', 'red', 'orange', 'blue', 'white', 'magenta', 'white'] },
        { cap: 7, fills: ['blue', 'magenta'] },
        { cap: 7, fills: ['red', 'blue', 'white'] },
        { cap: 7, fills: ['blue', 'red', 'magenta', 'slate'] },
        { cap: 7, fills: ['red', 'blue', 'red', 'blue', 'white', 'slate', 'orange'] },
        { cap: 7, fills: ['red', 'blue', 'red', 'red', 'orange', 'slate'] },
        { cap: 7, fills: ['red', 'blue', 'white', 'white', 'white'] }
      ]
    },
    {
      id: 'merge-46',
      mode: 'merge',
      name: 'Unspooled Orange',
      subtitle: 'Level 46 of 50',
      teaches: '7 jars · 31 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 9 },
      par: 31,
      path: [[3,2], [3,6], [2,3], [1,4], [2,1], [5,2], [5,6], [1,5], [4,1], [0,1], [0,4], [2,0], [5,2], [2,-1], [5,4], [4,2], [5,4], [4,-1], [5,4], [4,-1], [3,5], [3,4], [3,4], [4,-1], [6,3], [6,5], [0,4], [6,0], [0,-1], [0,6], [6,-1]],
      jars: [
        { cap: 7, fills: ['red', 'yellow', 'slate', 'white', 'purple'] },
        { cap: 7, fills: ['yellow', 'purple'] },
        { cap: 7, fills: ['red', 'red', 'red', 'slate', 'yellow', 'green'] },
        { cap: 7, fills: ['red', 'red', 'yellow', 'green', 'magenta', 'green'] },
        { cap: 7, fills: ['yellow', 'red', 'yellow', 'white', 'purple'] },
        { cap: 7, fills: ['yellow', 'red', 'white', 'yellow', 'magenta', 'slate'] },
        { cap: 7, fills: ['yellow', 'red', 'green', 'magenta'] }
      ]
    },
    {
      id: 'merge-47',
      mode: 'merge',
      name: 'Overlaid Orange',
      subtitle: 'Level 47 of 50',
      teaches: '7 jars · 32 moves',
      brief: "",
      target: 'orange',
      parents: ['red', 'yellow'],
      main: { cap: 10 },
      par: 32,
      path: [[5,2], [3,4], [0,4], [5,0], [0,-1], [0,5], [5,-1], [6,0], [0,5], [6,0], [0,-1], [6,0], [0,-1], [1,6], [1,3], [0,1], [3,0], [3,1], [1,-1], [2,3], [1,6], [4,2], [1,4], [4,-1], [5,1], [2,4], [5,2], [2,-1], [5,2], [2,-1], [2,5], [5,-1]],
      jars: [
        { cap: 7, fills: ['red', 'yellow', 'red', 'white', 'yellow', 'red', 'green'] },
        { cap: 7, fills: ['yellow', 'purple', 'red', 'slate', 'purple'] },
        { cap: 7, fills: ['yellow', 'red', 'yellow', 'green', 'magenta'] },
        { cap: 7, fills: ['yellow', 'yellow', 'slate', 'green'] },
        { cap: 7, fills: ['red', 'green'] },
        { cap: 7, fills: ['red', 'yellow', 'red', 'white', 'red', 'yellow', 'magenta'] },
        { cap: 7, fills: ['red', 'yellow', 'white'] }
      ]
    },
    {
      id: 'merge-48',
      mode: 'merge',
      name: 'Entwined Purple',
      subtitle: 'Level 48 of 50',
      teaches: '7 jars · 32 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 10 },
      par: 32,
      path: [[6,2], [1,2], [1,6], [6,1], [1,-1], [6,1], [1,-1], [6,1], [1,-1], [5,6], [2,6], [2,1], [1,-1], [4,1], [4,2], [2,-1], [5,4], [5,3], [5,1], [0,2], [3,0], [4,3], [4,5], [3,4], [3,2], [5,3], [3,-1], [0,3], [5,0], [0,-1], [0,5], [5,-1]],
      jars: [
        { cap: 7, fills: ['red', 'blue', 'orange', 'green'] },
        { cap: 7, fills: ['blue', 'red', 'blue', 'red', 'red', 'blue', 'white'] },
        { cap: 7, fills: ['blue', 'red', 'white'] },
        { cap: 7, fills: ['red', 'red', 'green', 'slate', 'orange'] },
        { cap: 7, fills: ['blue', 'slate', 'red', 'magenta'] },
        { cap: 7, fills: ['blue', 'red', 'blue', 'magenta', 'orange', 'slate', 'white'] },
        { cap: 7, fills: ['blue', 'red', 'blue', 'white'] }
      ]
    },
    {
      id: 'merge-49',
      mode: 'merge',
      name: 'Meshed Purple',
      subtitle: 'Level 49 of 50',
      teaches: '7 jars · 33 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 8 },
      par: 33,
      path: [[2,6], [4,2], [4,6], [1,4], [2,1], [0,2], [5,0], [0,-1], [4,5], [2,0], [1,2], [4,1], [1,-1], [0,4], [0,1], [1,0], [0,-1], [0,1], [1,-1], [6,0], [3,6], [3,2], [3,4], [2,1], [2,4], [3,2], [2,-1], [6,2], [3,4], [6,3], [3,-1], [3,6], [6,-1]],
      jars: [
        { cap: 7, fills: ['red', 'blue', 'blue', 'red', 'white', 'blue', 'white'] },
        { cap: 7, fills: ['blue', 'red', 'blue', 'green', 'orange'] },
        { cap: 7, fills: ['red', 'white', 'green', 'white', 'green', 'slate'] },
        { cap: 7, fills: ['red', 'blue', 'white', 'blue', 'white', 'green', 'magenta'] },
        { cap: 7, fills: ['red', 'orange', 'slate', 'green'] },
        { cap: 7, fills: ['red'] },
        { cap: 7, fills: ['blue', 'red', 'magenta', 'slate'] }
      ]
    },
    {
      id: 'merge-50',
      mode: 'merge',
      name: 'Roiled Purple',
      subtitle: 'Level 50 of 50',
      teaches: '7 jars · 34 moves',
      brief: "",
      target: 'purple',
      parents: ['red', 'blue'],
      main: { cap: 8 },
      par: 34,
      path: [[6,3], [1,6], [1,0], [2,1], [1,-1], [4,2], [1,5], [4,1], [1,-1], [6,1], [6,2], [5,4], [5,1], [4,5], [6,4], [4,-1], [5,4], [6,5], [5,-1], [2,6], [2,5], [5,-1], [3,2], [3,1], [0,5], [0,1], [3,0], [0,-1], [3,0], [0,-1], [6,3], [0,5], [0,6], [6,-1]],
      jars: [
        { cap: 7, fills: ['red', 'green', 'red', 'blue', 'slate', 'green'] },
        { cap: 7, fills: ['blue', 'white', 'blue', 'green', 'slate'] },
        { cap: 7, fills: ['red', 'magenta', 'red'] },
        { cap: 7, fills: ['blue', 'red', 'slate', 'orange'] },
        { cap: 7, fills: ['blue', 'white', 'red', 'magenta'] },
        { cap: 7, fills: ['blue', 'red', 'white', 'slate', 'white'] },
        { cap: 7, fills: ['blue', 'magenta', 'blue', 'red', 'magenta', 'slate', 'orange'] }
      ]
    }
  ];

  global.MergeLevels = {
    list: LEVELS,
    byId: function (id) {
      for (var i = 0; i < LEVELS.length; i++) if (LEVELS[i].id === id) return LEVELS[i];
      return null;
    },
    indexOf: function (id) {
      for (var i = 0; i < LEVELS.length; i++) if (LEVELS[i].id === id) return i;
      return -1;
    }
  };
})(typeof window !== 'undefined' ? window : globalThis);
