#!/usr/bin/env node
/* fetch-fonts.js — regenerate fonts.css.
 *
 *   node fetch-fonts.js
 *
 * Downloads the latin subset of the three faces from Google Fonts and writes
 * them into fonts.css as data URIs. Inlining rather than linking means the
 * game keeps its typography with no network at all — opened from disk, or
 * published somewhere that blocks external hosts. Only needs re-running if
 * the type stack changes. */

'use strict';
const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

/* Google serves woff2 only to browsers it recognises. */
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';
const API = 'https://fonts.googleapis.com/css2?family=' + [
  'Baloo+2:wght@700;800',
  'Nunito:wght@600;700;800'
].join('&family=') + '&display=swap';

const curl = (url, binary) =>
  execFileSync('curl', ['-sS', '--max-time', '60', '-A', UA, url],
    { maxBuffer: 64 * 1024 * 1024, encoding: binary ? 'buffer' : 'utf8' });

console.log('fetching stylesheet…');
const css = curl(API, false);

/* Each @font-face is preceded by a subset comment. Keep latin only: the game
 * has no other scripts in it, and the rest would triple the size. */
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g)]
  .filter(m => m[1] === 'latin')
  .map(m => m[2]);

if (!blocks.length) throw new Error('no latin @font-face blocks found');

let total = 0;
const out = blocks.map(block => {
  const url = block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)[1];
  const family = block.match(/font-family:\s*'([^']+)'/)[1];
  const weight = (block.match(/font-weight:\s*([^;]+)/) || [, '?'])[1].trim();
  const bytes = curl(url, true);
  total += bytes.length;
  console.log('  ' + family + ' ' + weight + '  ' + (bytes.length / 1024).toFixed(1) + ' KB');
  return block
    .replace(/url\([^)]+\)/, "url(data:font/woff2;base64," + bytes.toString('base64') + ")")
    .replace(/\n\s*unicode-range:[^;]+;/, '');   /* latin-only: range is redundant */
}).join('\n');

const dest = path.join(__dirname, 'fonts.css');
fs.writeFileSync(dest,
  '/* GENERATED by fetch-fonts.js — do not edit by hand.\n' +
  '   Latin subsets of the three faces, inlined as data URIs so the game\n' +
  '   renders its own typography with no network dependency. */\n\n' + out + '\n');

console.log('wrote fonts.css  (' + (fs.statSync(dest).size / 1024).toFixed(0) + ' KB, ' +
            blocks.length + ' faces, ' + (total / 1024).toFixed(0) + ' KB of font data)');
